### ISSUE TITLE
Destination /etc/monit not writable

### ISSUE THREAD

**Issue by prettynatty** [ANXS/monit#6]
Latest monit version requires /etc/monit/monitrc to have -rw------- rights. But if I set such rights "Update the monit configuration" task fails with "Destination /etc/monit not writable" even if I set `sudo: yes` for the role.

**Comment by soupdiver** [comment]
Are you speaking of the latest version provided by Ubuntu or monit at all?

**Comment by prettynatty** [comment]
I am speaking about latest version provuded by Ubuntu: 5.6

**Comment by prettynatty** [comment]
If I set `sudo: yes` for the whole playbook, everything works fine, but if I specify sudo just for role:
```
- hosts: appservers
  roles:
    - role: ANXS.monit
      sudo: yes
```
the error appears.

**Comment by soupdiver** [comment]
I just started a VM based on the provided `Vagrantfile` and monit starts without any problem.
Also the file seems to have the correct permissions:
```
ls -la /etc/monit/
total 28
drwxr-xr-x  5 root root 4096 Apr 16 01:41 .
drwxr-xr-x 94 root root 4096 Apr 16 01:41 ..
drwxr-xr-x  2 root root 4096 Apr 16 01:41 conf.d
-rw-------  1 root root 6402 Apr 16 01:41 monitrc
drwxr-xr-x  2 root root 4096 Apr 16 01:41 monitrc.d
drwxr-xr-x  2 root root 4096 Apr 16 01:41 templates
```

Did you upgraded from a previous version of monit?

**Comment by prettynatty** [comment]
You have `ansible.sudo = true` set to true which is equivalent to setting `sudo: yes` for the whole playbook with which my case works too. The problem appears if there is no `sudo: yes` for the whole playbook but it is set for the role only.

**Comment by otakup0pe** [comment]
I'm not sure that `sudo` is expected to work that way with roles. I don't believe this is actually a bug with the `ANXS.monit` role.

**Comment by soupdiver** [comment]
Houh I'm not sure if you can set `sudo: yes` for a specific role.
I think it  should be set on a task or playbook level
